### PR TITLE
BUG: Increase validator types for thie 'input' parameter of embeddings to match OpenAI API

### PR DESCRIPTION
**Pull request by Minamiyama**
image

### CODE REVIEW

**Comment by qinxuye** [comment]
Lint failed, could you fix it?

**Comment by Minamiyama** [comment]
> Lint failed, could you fix it?

I have no idea where the problem is.

**Comment by qinxuye** [comment]
See https://github.com/xorbitsai/inference/actions/runs/8460003388/job/23177384826?pr=1201

You may need to install black and use it to format your code.

**Comment by Minamiyama** [comment]
> See https://github.com/xorbitsai/inference/actions/runs/8460003388/job/23177384826?pr=1201
> 
> You may need to install black and use it to format your code.

done

**Review by qinxuye — APPROVED** [review]
LGTM

**Comment by qinxuye** [comment]
Have you tried if it works?

**Comment by Minamiyama** [comment]
> Have you tried if it works?

yes, of cos. it caused a problem for me, fixed it and solved the problem

**Pull request merged**
