### PR TITLE
FEAT: new model: mini-cpm-llama3-v-2.5

### PR DESCRIPTION
**Pull request by Minamiyama**
https://github.com/xorbitsai/inference/assets/918617/2e40c6e5-6076-449e-9cc2-5fb363f29e48

### CODE REVIEW

**Comment by amumu96** [comment]
Great job! @Minamiyama 
I checkout your branch and try to run this model... how do you solve this error?
image
It seems when the model import `transformers_modules.MiniCPM-Llama3-V-2.5-pytorch-8b`, regard `MiniCPM-Llama3-V-2` is a module, and cannot find it

**Comment by Minamiyama** [comment]
> Great job! @Minamiyama I checkout your branch and try to run this model... how do you solve this error? image It seems when the model import `transformers_modules.MiniCPM-Llama3-V-2.5-pytorch-8b`, regard `MiniCPM-Llama3-V-2` is a module, and cannot find it

I got the problem, the model name could not be with 2.5, it should be like 2_5, and I've fix it.

**Comment by Minamiyama** [comment]
> Great job! @Minamiyama I checkout your branch and try to run this model... how do you solve this error? image It seems when the model import `transformers_modules.MiniCPM-Llama3-V-2.5-pytorch-8b`, regard `MiniCPM-Llama3-V-2` is a module, and cannot find it

but the model name in UI model card is shown as "MiniCPM-Llama3-V-2 5", how make it show as "MiniCPM-Llama3-V-2.5" without  this error🤣

**Comment by amumu96** [comment]
> > Great job! @Minamiyama I checkout your branch and try to run this model... how do you solve this error? image It seems when the model import `transformers_modules.MiniCPM-Llama3-V-2.5-pytorch-8b`, regard `MiniCPM-Llama3-V-2` is a module, and cannot find it
> 
> but the model name in UI model card is shown as "MiniCPM-Llama3-V-2 5", how make it show as "MiniCPM-Llama3-V-2.5" without this error🤣

How about replacing `_` or `-`  to `.` in model name when read and write cache?

**Comment by Minamiyama** [comment]
> > > Great job! @Minamiyama I checkout your branch and try to run this model... how do you solve this error? image It seems when the model import `transformers_modules.MiniCPM-Llama3-V-2.5-pytorch-8b`, regard `MiniCPM-Llama3-V-2` is a module, and cannot find it
> > 
> > 
> > but the model name in UI model card is shown as "MiniCPM-Llama3-V-2 5", how make it show as "MiniCPM-Llama3-V-2.5" without this error🤣
> 
> How about replacing `_` or `-` to `.` in model name when read and write cache?

I have no idea about where to do that😭

**Review by amumu96 — APPROVED** [review]

**Comment by qinxuye** [comment]
Thanks, about the dot in name, we will fix it later.

**Pull request merged**
