### PR TITLE
BUG: tts stream mode not working

### PR DESCRIPTION
**Pull request by leslie2046**
Close:https://github.com/xorbitsai/inference/issues/2269

### CODE REVIEW

**Comment by qinxuye** [comment]
You can install `pre-commit`, and when cd inference directory, run `pre-commit install`, it will install the black & flake so forth, when you commit, it will format the code with black and check flake8 for you in advance.

**Comment by leslie2046** [comment]
> You can install `pre-commit`, and when cd inference directory, run `pre-commit install`, it will install the black & flake so forth, when you commit, it will format the code with black and check flake8 for you in advance.

done

**Comment by leslie2046** [comment]
> What version of xinference_client are you using?

0.15.0

**Comment by leslie2046** [comment]
你确定不是一瞬间收到了这些数据吗，我试过如果requests.post里不传stream=True,我也会像你这样收到一块一块的数据，但是是一瞬间收到的；
而如果传stream=True,会在请求后陆陆续续收到这些数据的。

**Comment by qinxuye** [comment]
Thanks for your contribution.

**Comment by leslie2046** [comment]
> I got it. The requests.post is not a stream operation.

yep

**Pull request merged**
