### PR TITLE
FEAT: support scheduling-policy for vllm

### PR DESCRIPTION
**Pull request by hwzhuhao**
since version 0.6.3, the AsyncLLMEngine in vllm supports priority scheduling (https://github.com/vllm-project/vllm/pull/8850)，so add a new parameter "scheduling-policy" for the vllm model config to support priority scheduling.

### CODE REVIEW

**Comment by qinxuye** [comment]
Oh, I wrongly thought this solved #2669 , besides the scheduling policy, we can support priority as well right?

**Comment by hwzhuhao** [comment]
yes, but need to set the scheduling policy to priority, the default value is fcfs

**Comment by qinxuye** [comment]
> yes, but need to set the scheduling policy to priority, the default value is fcfs

OK, can you add the priority option in this PR?

**Comment by hwzhuhao** [comment]
user can set the scheduling policy to priority by passing custom parameters when launching models with the vllm inference engine, whether through the interface or the command line. I didn't quite understand the specific meaning for add the priority option. Could you please elaborate further?

**Comment by qinxuye** [comment]
> user can set the scheduling policy to priority by passing custom parameters when launching models with the vllm inference engine, whether through the interface or the command line. I didn't quite understand the specific meaning for add the priority option. Could you please elaborate further?

Indeed, the priority is an generation option, never mind, let’s check it later.

**Review by qinxuye — APPROVED** [review]
LGTM

**Pull request merged**
