### PR TITLE
FEAT: qwen2-instruct support tool call

### PR DESCRIPTION
**Pull request by ayhhyhh**
Qwen2 is not on the whitelist for function calls. Add it to support function calls.

### CODE REVIEW

**Comment by zhanghx0905** [comment]
https://github.com/xorbitsai/inference/blob/f9b879cb096e1365c2ffe65abbc7f21f4a4de357/xinference/api/restful_api.py#L1430
Please change here as well

**Comment by codingl2k1** [comment]
Please run this unittest (test_restful_api.py::test_restful_api_for_qwen_tool_calls) as well, may need some modifications for qwen2-instruct: https://github.com/xorbitsai/inference/blob/main/xinference/core/tests/test_restful_api.py#L728

**Comment by codingl2k1** [comment]
Fixes: https://github.com/xorbitsai/inference/issues/1630

**Comment by codingl2k1** [comment]
I ran the test locally. It works well.

**Review by codingl2k1 — APPROVED** [review]
LGTM

**Pull request merged**
