### PR TITLE
FEAT: embedding launch

### LINKED ISSUE #544: FEAT: launch embedding models in Web UI

### PR DESCRIPTION
**Pull request by Minamiyama**
image
image

resolve #544

### CODE REVIEW

**Comment by Minamiyama** [comment]
#544

**Comment by aresnow1** [comment]
@Minamiyama Can we create two tabs on the launch model page? One for LLM and the other for embedding.

**Comment by Minamiyama** [comment]
> @Minamiyama Can we create two tabs on the launch model page? One for LLM and the other for embedding.

wow, good idea, you do it or I do it?

**Comment by aresnow1** [comment]
> > @Minamiyama Can we create two tabs on the launch model page? One for LLM and the other for embedding.
> 
> wow, good idea, you do it or I do it?

You can go ahead, I'm not very good at this.

**Comment by Minamiyama** [comment]
image
image


done! @aresnow1

**Comment by aresnow1** [comment]
Great job, we will review later.

**Comment by UranusSeven** [comment]
Hello, the git history shows unrelated commits. These need to be resolved before merging this Pull Request to the main branch. Given the confusion in the commits, creating a new pull request might be the better choice.

I have rebased and merged all your changes into this patch for you. Please create a new branch, download, and apply this patch using the following command:

```bash
git apply /path/to/0001-FEAT-launch-embedding-models.patch
```

Afterward, create a new pull request from the new branch.


[0001-FEAT-launch-embedding-models.patch](https://github.com/xorbitsai/inference/files/13174968/0001-FEAT-launch-embedding-models.patch)

**Comment by UranusSeven** [comment]
@Minamiyama And again, thanks for your contribution :)

**Comment by UranusSeven** [comment]
Moving to #582.

**Pull request closed without merging**
