### PR TITLE
ENH: add normalize to rerank model

### PR DESCRIPTION
**Pull request by hustyichi**
The current Rerank model return value is not normalized. FlagEmbedding provides a normalization option. It is recommended to return the normalized value.

### CODE REVIEW

**Comment by hustyichi** [comment]
The current return value is as follows：

**Comment by qinxuye** [comment]
Should the If normalize, what's the result?

**Comment by hustyichi** [comment]
The structure of the result is the same, except that the values ​​are normalized to be between 0 and 1

The corresponding implementation in FlagEmbedding is as follows
```
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

for i in range(len(all_scores)):
    all_scores[i] = [all_scores[i][idx] for idx in np.argsort(length_sorted_idx)]
    if normalize:
          all_scores[i] = [sigmoid(score) for score in all_scores[i]]
```

**Comment by qinxuye** [comment]
OK, looks like this will not effect the result, but I don't if this will cause any side effect. @codingl2k1 What's your opinion?

**Comment by qinxuye** [comment]
> > OK, looks like this will not effect the result, but I don't know if this will cause any side effect. @codingl2k1 What's your opinion?
> 
> This will be a breaking change. Since FlagEmbedding sets normalize to False by default, how about we keep normalize set to False by default and allow users to set normalize in kwargs?

OK, @hustyichi What's your idea? is it possible to add kwargs to rerank and allow setting normalize to True?

**Comment by hustyichi** [comment]
> > > OK, looks like this will not effect the result, but I don't know if this will cause any side effect. @codingl2k1 What's your opinion?
> > 
> > 
> > This will be a breaking change. Since FlagEmbedding sets normalize to False by default, how about we keep normalize set to False by default and allow users to set normalize in kwargs?
> 
> OK, @hustyichi What's your idea? is it possible to add kwargs to rerank and allow setting normalize to True?

This is a good idea, but requires more code

**Comment by hustyichi** [comment]
I added the always_normalize option, which is not enabled by default

**Review by qinxuye — APPROVED** [review]
LGTM

**Pull request merged**
