### PR TITLE
FEAT: Added a method to download models from csghub. 

### PR DESCRIPTION
**Pull request by hainaweiben**
This can be utilized by setting the environment variable `XINFERENCE_MODEL_SRC="csghub"`. Additionally, you need to set `XINFERENCE_CSG_TOKEN` to your csghub login token. Please note that currently, the qwen2 model library on csghub has been removed and is temporarily unavailable for download.

### CODE REVIEW

**Review by qinxuye — APPROVED** [review]
LGTM

**Review by qinxuye — APPROVED** [review]
LGTM

**Comment by KinglyWayne** [comment]
Maybe we should change csghub endpoint from "https://hub-stg.opencsg.com" to "https://hub.opencsg.com" for production usage

**Comment by qinxuye** [comment]
> Maybe we should change csghub endpoint from "https://hub-stg.opencsg.com" to "https://hub.opencsg.com" for production usage

Could you open a PR to fix it?

I think it could be a environment as well, we can use production as default.

**Comment by hainaweiben** [comment]
> Maybe we should change csghub endpoint from "https://hub-stg.opencsg.com" to "https://hub.opencsg.com" for production usage

According to this document, the endpoint should be "https://hub-stg.opencsg.com/".

**Pull request merged**
