### PR TITLE
ENH: Add Environment Variable to Disable QWEN vllm Tools Response Filter

### PR DESCRIPTION
**Pull request by zhanghx0905**
This PR introduces a new environment variable, XINFERENCE_DISABLE_QWEN_REACT_RESPONSE_FILTER, to disable the QWEN vllm's tool call response filtering mechanism.

Xinference will by default enable the QWEN vllm's tool call ReAct response filtering.
Users will only see what comes after the "Final Answer" in QWEN's ReAct response.

Setting this environment to 1 will disable the response filtering mechanism, 
allowing raw responses from QWEN vllm tools to be returned without additional processing.

To disable filtering:

```sh
export XINFERENCE_DISABLE_QWEN_REACT_RESPONSE_FILTER=1
```

#1685

image

### CODE REVIEW

**Comment by fyrestone** [comment]
Does this work well with continuous chat, as all the output will be contained in the next chat messages? For example, chat with the previous tool call result.

**Comment by codingl2k1** [comment]
Does this work well with continuous chat, as all the output will be contained in the next chat messages? For example, chat with the previous tool call result.

**Comment by zhanghx0905** [comment]
> Does this work well with continuous chat, as all the output will be contained in the next chat messages? For example, chat with the previous tool call result.

You're right, enabling this option will cause more information to be included in the history. It does have the potential to affect subsequent tool calls, especially for smaller models.

But as suggested in the cited issue, users can choose how to use chat history on the client side, and they can implement their own filtering policies.

**Comment by zhanghx0905** [comment]
I suddenly realized there are actually multiple scenarios to consider. For example, what kind of reasoning backend to use (vllm or not) and whether to enable stream response or not. My PR only considered the case where vllm is used and stream is enabled so it shouldn't be merged now.

**Pull request closed without merging**
