### PR TITLE
ENH: make qwen_vl support streaming output

### PR DESCRIPTION
**Pull request by Minamiyama**

### CODE REVIEW

**Comment by fyrestone** [comment]
Could you add some unit tests? We don't run them in our CI because of resource limitations, but we can use them to check the code during development. https://github.com/xorbitsai/inference/blob/main/xinference/model/llm/tests/test_multimodal.py#L24

**Comment by codingl2k1** [comment]
Could you add some unit tests? We don't run them in our CI because of resource limitations, but we can use them to check the code during development. https://github.com/xorbitsai/inference/blob/main/xinference/model/llm/tests/test_multimodal.py#L24

**Comment by Minamiyama** [comment]
> Could you add some unit tests? We don't run them in our CI because of resource limitations, but we can use them to check the code during development. https://github.com/xorbitsai/inference/blob/main/xinference/model/llm/tests/test_multimodal.py#L24

how about this⬇️ record video？
https://github.com/xorbitsai/inference/assets/918617/5d975b58-cc02-4e27-b5bf-d059be8a4c7f

**Review by qinxuye — APPROVED** [review]
LGTM, excellent work.

**Pull request merged**
