### PR TITLE
FEAT: Ascend support

### LINKED ISSUE #1323: Ascend support
### Is your feature request related to a problem? Please describe
No

### Describe the solution you'd like
As Ascend from Huawei is getting more and more attention in China market. Please support Ascend in xInference. 

### Describe alternatives you've considered
May be integrate FastChat as backend is a shortcut to implement this feature.  FastChat announced it supports Ascend NPU. And according to our test, FastChat DOES support Ascend.  FastChat also support exllamav2 as a plus for CUDA architecture. 

### Additional context
SOE in China was asked to adapt local AI hardware vendor such as Ascend, 寒武纪, etc.

### PR DESCRIPTION
**Pull request by qinxuye**
Ascend support is tested.

## Chat

Tested Qwen 7b.

image

### gpu_idx=3

image

### gpu_idx=0,2

image

## Some issues

HuggingFace accelerate and timm is imported in OmniLMM, both will cause torch_npu imported which will cause that `ASCEND_RT_VISIBLE_DEVICES` not work, so I put the imports into the functions.

## Cuda

I tested both qwen1.5 and OmniLMM on cuda devices, they work well.

Fixes #1323

### CODE REVIEW

**Review by ChengjieLi28 — APPROVED** [review]

**Comment by Halfknow** [comment]
When I install xinference by pip3.10 install xinference["transformers"] in ascend npu device, I encountered the install error when pip installing auto-gpt, since it didn't recognizing torch module. But I've installed torch-npu manually by the torch-npu wheel file. I wonder how to install xinference successfally.

**Comment by qinxuye** [comment]
The doc will be released soon. For a short explain. Try

```
# ensure torch and torch_npu installed
pip install transformers
pip install xinference
```

That should work. Can you try?

**Comment by Halfknow** [comment]
> The doc will be released soon. For a short explain. Try
> 
> ```
> # ensure torch and torch_npu installed
> pip install transformers
> pip install xinference
> ```
> 
> That should work. Can you try?

In the latest version, follow the step in this tutorial: https://inference.readthedocs.io/en/latest/getting_started/installation_npu.html.

After pip3 install xinference,  then run xinference-local, the error shows: 

`[root@bms-dsjtz-0001 ~]# xinference-local
Traceback (most recent call last):
  File "/usr/local/bin/xinference-local", line 5, in <module>
    from xinference.deploy.cmdline import local
  File "/usr/local/lib/python3.10/site-packages/xinference/__init__.py", line 37, in <module>
    _install()
  File "/usr/local/lib/python3.10/site-packages/xinference/__init__.py", line 34, in _install
    install_model()
  File "/usr/local/lib/python3.10/site-packages/xinference/model/__init__.py", line 25, in _install
    llm_install()
  File "/usr/local/lib/python3.10/site-packages/xinference/model/llm/__init__.py", line 153, in _install
    from .vllm.core import VLLMChatModel, VLLMModel, VLLMVisionModel
  File "/usr/local/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 137, in <module>
    if VLLM_INSTALLED and vllm.__version__ >= "0.3.0":
AttributeError: module 'vllm' has no attribute '__version__'`

Actually, I've installed the ascend version vllm, but the error is still there. I wonder how to fix that and use transformers as backend to inference llms.

**Comment by xinghuiiiiiiiii** [comment]
Hi, is there any plan to support ascend's atb accelerated offline inference in the future?

**Comment by qinxuye** [comment]
> Hi, is there any plan to support ascend's atb accelerated offline inference in the future?

That will be included only for enterprise version.

**Pull request merged**
