### PR TITLE
BUG: Fixing the issue of model list loading failure caused by a large number of invalid requests on the model list page.

### LINKED ISSUE #1110: BUG-前端页面请求模型列表无效请求过多，导致页面模型列表经常无法展示
在模型Lanuch Model 页面， 存在太多不合理的无效请求，每个模型都会单独请求一次接口，完全返回后才能展示模型列表，只要有一个失败，由于JS 报错，整个模型列表就无法展示，导致模型列表经常空白，其中LLM 偶尔可以正常返回，embedding 列表从来没有展示出来过
image
请求分析：
image
其中 ，左上角红框中的接口已经返回了完整的模型列表及详情数据，然而，后面的又对每个模型发起了一次请求，由于同时发起的请求数过多，部分请求会异常超时(猜测此处应该是因为大量请求同时进入服务端,服务端阻塞导致)

一方面这种处理方式，只能在模型数量较小时工作，当模型数量达到一定量级后，对服务端的压力会很大，另一个方面也会导致整个模型列表页面性能非常差

如下图，左侧为单独模型的详情接口返回值，右侧为列表中一项元素的返回值，可以看到列表接口返回的内容完全覆盖了详情接口
image

[相关的代码实现](https://github.com/xorbitsai/inference/blob/2a45c84e76a85f53f35d71455df3b75ba3dd48ba/xinference/web/ui/src/scenes/launch_model/launchEmbedding.js)
红框中的这部分处理是完全没有必要的
image

修复建议，删除最后一张图中红框部分的代码， 同时该问题在embedding，rerank，image 这几个页面都存在， 稍后，我会尝试提交一个PR来修复

### PR DESCRIPTION
**Pull request by wertycn**
Fixes #1110 

修复后效果如图：
image
切换模型tab 只会发起一次请求，同时，模型列表可以正常加载

### CODE REVIEW

**Comment by ChengjieLi28** [comment]
@wertycn Run `npm run format` under the `xinference/web/ui` dir to pass the lint check.

**Comment by ChengjieLi28** [comment]
Also, please rebase to the latest main code to run the CI.

**Comment by wertycn** [comment]
> @wertycn Run `npm run format` under the `xinference/web/ui` dir to pass the lint check.

Already processed.

**Review by ChengjieLi28 — APPROVED** [review]

**Comment by qinxuye** [comment]
Thank you for your contribution.

**Pull request merged**
