### PR TITLE
BUG: fix embedding model gte-Qwen2 dimensions

### LINKED ISSUE #2471: gte-Qwen2 Incorrect model information / 模型信息有误
### System Info / 系統信息

无关

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.16.0

### The command used to start Xinference / 用以启动 xinference 的命令

nohup xinference-local --host 0.0.0.0 --port 49640 --log-level DEBUG &

### Reproduction / 复现过程

xinference官方文档显示，gte-qwen2的维度为3584
https://inference.readthedocs.io/en/latest/models/builtin/embedding/gte-qwen2.html
image

hf官方xian显示，gte-qwen2的维度为4096
https://huggingface.co/Alibaba-NLP/gte-Qwen1.5-7B-instruct

modelscope显示结果与hf相同，均为4096
https://modelscope.cn/models/iic/gte_Qwen1.5-7B-instruct/summary
image

### Expected behavior / 期待表现

修正文档及相关配置

### PR DESCRIPTION
**Pull request by JinCheng666**
Fixes #2471 
fix embedding model gte-Qwen2 dimensions

> wrong dimensions：
> 
> https://github.com/xorbitsai/inference/blob/48a07e8af3d015908c8a55f91c7baea3afbbb809/xinference/model/embedding/model_spec.json#L236C1-L237C1
> 
> correct dimensions：
> 
> https://github.com/xorbitsai/inference/blob/48a07e8af3d015908c8a55f91c7baea3afbbb809/xinference/model/embedding/model_spec_modelscope.json#L238

base on the right message：
https://huggingface.co/Alibaba-NLP/gte-Qwen1.5-7B-instruct
https://modelscope.cn/models/iic/gte_Qwen1.5-7B-instruct/summary

### CODE REVIEW

**Review by JinCheng666 — COMMENTED** [review]
right

**Comment by JinCheng666** [comment]
I don't know if this PR conforms to the project rules, please point out if there is anything wrong

**Comment by JinCheng666** [comment]
i dont know why the python3.11 check fail. it seems like not problems with the code.
 how to rerun the checks? @qinxuye

**Comment by qinxuye** [comment]
> i dont know why the python3.11 check fail. it seems like not problems with the code. how to rerun the checks? @qinxuye

That's OK, can you run `python doc/source/gen_docs.py`?

This will change many files, you can revert but the gte-qwen2.rst then commit.

https://github.com/xorbitsai/inference/blob/main/doc/source/models/builtin/embedding/gte-qwen2.rst

**Comment by JinCheng666** [comment]
> > i dont know why the python3.11 check fail. it seems like not problems with the code. how to rerun the checks? @qinxuye
> 
> That's OK, can you run `python doc/source/gen_docs.py`?
> 
> This will change many files, you can revert others but the `gte-qwen2.rst` then commit.
> 
> https://github.com/xorbitsai/inference/blob/main/doc/source/models/builtin/embedding/gte-qwen2.rst

I ran the code locally and got an error, so I manually adjusted the contents of the file, not sure if it was appropriate？

**Comment by qinxuye** [comment]
> > > i dont know why the python3.11 check fail. it seems like not problems with the code. how to rerun the checks? @qinxuye
> > 
> > 
> > That's OK, can you run `python doc/source/gen_docs.py`?
> > This will change many files, you can revert others but the `gte-qwen2.rst` then commit.
> > https://github.com/xorbitsai/inference/blob/main/doc/source/models/builtin/embedding/gte-qwen2.rst
> 
> I ran the code locally and got an error, so I manually adjusted the contents of the file, not sure if it was appropriate？
> 
> window pc，The error information is as follows：
> 
> ```shell
> PS D:\work\code\inference\doc\source> python .\gen_docs.py
> Traceback (most recent call last):
>   File "D:\work\code\inference\doc\source\gen_docs.py", line 284, in <module>
>     main()
>   File "D:\work\code\inference\doc\source\gen_docs.py", line 54, in main
>     models = json.load(model_file)
>   File "C:\Users\liujincheng\.conda\envs\openaitest\lib\json\__init__.py", line 293, in load
>     return loads(fp.read(),
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 7227: illegal multibyte sequence
> ```

Should be OK, let's wait for CI to complete.

**Comment by JinCheng666** [comment]
> > > > i dont know why the python3.11 check fail. it seems like not problems with the code. how to rerun the checks? @qinxuye
> > > 
> > > 
> > > That's OK, can you run `python doc/source/gen_docs.py`?
> > > This will change many files, you can revert others but the `gte-qwen2.rst` then commit.
> > > https://github.com/xorbitsai/inference/blob/main/doc/source/models/builtin/embedding/gte-qwen2.rst
> > 
> > 
> > I ran the code locally and got an error, so I manually adjusted the contents of the file, not sure if it was appropriate？
> > window pc，The error information is as follows：
> > ```shell
> > PS D:\work\code\inference\doc\source> python .\gen_docs.py
> > Traceback (most recent call last):
> >   File "D:\work\code\inference\doc\source\gen_docs.py", line 284, in <module>
> >     main()
> >   File "D:\work\code\inference\doc\source\gen_docs.py", line 54, in main
> >     models = json.load(model_file)
> >   File "C:\Users\liujincheng\.conda\envs\openaitest\lib\json\__init__.py", line 293, in load
> >     return loads(fp.read(),
> > UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 7227: illegal multibyte sequence
> > ```
> 
> Should be OK, let's wait for CI to complete.

so cool, my first pr is coming soon...

**Review by qinxuye — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by JinCheng666** [comment]
> LGTM, thanks for your contribution!

thank you vary much ! happy 1024 day！ @qinxuye

**Pull request merged**
