### PR TITLE
ENH: make deepseek_vl support streaming output

### PR DESCRIPTION
**Pull request by Minamiyama**
https://github.com/xorbitsai/inference/assets/918617/fcf799c3-050a-4097-9674-62d8a3b211fa

### CODE REVIEW

**Comment by sunhaha123** [comment]
Looks great! Could this model run on 24gb gpu?

**Comment by sunhaha123** [comment]
> Looks great! Could this model run on 24gb gpu?

seems fp16 works.

**Comment by Minamiyama** [comment]
> Looks great! Could this model run on 24gb gpu?

yes, I run it on gtx4090

**Comment by sunhaha123** [comment]
ModuleNotFoundError: [address=0.0.0.0:42331, pid=2580143] No module named 'xinference.thirdparty.deepseek_vl.
I pip install after git pull from main branch. Occur this problem.

**Comment by Minamiyama** [comment]
> ```
>   File "/home/echo/miniconda3/envs/xinfer/lib/python3.10/site-packages/xinference/model/llm/pytorch/deepseek_vl.py", line 190, in chat
>     from ....thirdparty.deepseek_vl.serve.inference import generate
> ModuleNotFoundError: [address=0.0.0.0:42331, pid=2580143] No module named 'xinference.thirdparty.deepseek_vl.serve'
> ```
> 
> I pip install after git pull from main branch. Occur this problem.

the module codes is in source codes:
image


maybe you should build from source code, or put the codes in xinference/thirdparty/deepseek_vl to your package path (I solved it by this way)

**Comment by sunhaha123** [comment]
> maybe you should build from source code, or put the codes in xinference/thirdparty/deepseek_vl to your package path (I solved it by this way)

It works. Still feeling strange, I do pip install from source code.

**Comment by qinxuye** [comment]
Did you update the main code?

**Comment by sunhaha123** [comment]
> Did you update the main code?

git pull origin main

**Comment by sunhaha123** [comment]
> Did you update the main code?

git pull origin main, and pip install .[transformers]

**Comment by dimitribellini** [comment]
Dear Team,
I'm new to "xinference" and I do not understand so well on how to use your inference server and the Deepseek VL model.
Using the docker option I was able to run it and load the module using the engine option "transformer" but as soon a connect using OpenWebUI through the OpenAI API I received the message reported from @Minamiyama 
How I can solve it? Your help it's very appreciate :-) 
Thanks so much

**Pull request merged**
