### PR TITLE
BUG: Infinited loop with login

### LINKED ISSUE #2021: 前端页面无限跳转登录页问题
### System Info / 系統信息

前端页面打开后，无限跳转登录和launch/llm页面
经过排查，是因为我的本地浏览器有一个默认的token cookie, 导致 这里的判断过不去，所以不会设置no_auth 的 cookie
https://github.com/xorbitsai/inference/blob/3f7dc2ddccfd023dc3aabee7200891de6a60eee0/xinference/web/ui/src/App.js#L40

建议 去除 `if (!data.auth && cookie.token !== 'no_auth')` 中 `cookie.token !== 'no_auth'` 这个判断逻辑
或 
更换cookie的key值：例如xinference-token

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -p 9997:9997 --gpus all xprobe/xinference:v0.14.0 xinference-local -H 0.0.0.0

### Reproduction / 复现过程

1. 浏览器先设置一个token的cookie

### Expected behavior / 期待表现

改进cookie和sessionStorage的key值

### PR DESCRIPTION
**Pull request by WalkerWang731**
Fixes #2021

Details:
1. Added new keys `auth` and `token` in `sessionStore` to avoid conflicts with existing cookie key names.
2. Optimized the authentication logic within each page. The new logic replaces the original code as follows:
```
if (!sessionStorage.getItem('auth') &&
    sessionStorage.getItem('token') !== 'no_auth' && cookie.token !== 'no_auth'
){
    navigate('/login', { replace: true });
}
```

3. Updated the corresponding `sessionStorage.setItem('token')` / `sessionStorage.setItem('auth')` and `sessionStorage.removeItem('token')` / `sessionStorage.removeItem('auth')` logic accordingly.

### CODE REVIEW

**Comment by yiboyasss** [comment]
When the user logs out and clicks the button in the upper left corner of the browser to return to the previous page, they should not enter the internal system.
截屏2024-08-09 11 53 26

**Comment by WalkerWang731** [comment]
> When the user logs out and clicks the button in the upper left corner of the browser to return to the previous page, they should not enter the internal system. 截屏2024-08-09 11 53 26

I have already fixed the relevant code and updated the logic to:
```
  if (
    sessionStorage.getItem('auth') === 'true' &&
    !isValidBearerToken(sessionStorage.getItem('token')) &&
    !isValidBearerToken(cookie.token)
  ) {
    navigate('/login', { replace: true })
  }
```
it's working now

**Comment by yiboyasss** [comment]
After logging out, open a new page and enter the corresponding path. You should not enter the system.

**Comment by WalkerWang731** [comment]
> After logging out, open a new page and enter the corresponding path. You should not enter the system.

yes, now it can't access the system when clicked the logout button

**Comment by WalkerWang731** [comment]
Hello, @yiboyasss @qinxuye 
I'm aware of this PR has not been merged yet. May I know do you have any concerns about this PR now?
I've fixed the lastest problem that when clicking the logout button, the page can still be opened.
Here is the commit: https://github.com/xorbitsai/inference/pull/2039/commits/77042026c99edfd3361df31f1f1cbe161279b8cc

Any questions please let me know.
Thank you

**Comment by yiboyasss** [comment]
We hope it's not a prompt to enter the page, but a direct inability to enter.
截屏2024-08-13 11 16 23

**Comment by WalkerWang731** [comment]
> We hope it's not a prompt to enter the page, but a direct inability to enter. 截屏2024-08-13 11 16 23

Hello @yiboyasss
I've fixed this problem
Please refer to the lastest commit: https://github.com/xorbitsai/inference/pull/2039/commits/7f7bd9b784f5c7e972cf489df52f71504b67acf0

Any questions please let me know
Thank you

**Comment by yiboyasss** [comment]
> After logging out, open a new page and enter the corresponding path. You should not enter the system.

A new question always has pop-up prompts, which are unnecessary.
截屏2024-08-14 10 30 20

**Comment by WalkerWang731** [comment]
> > After logging out, open a new page and enter the corresponding path. You should not enter the system.
> 
> A new question always has pop-up prompts, which are unnecessary. 截屏2024-08-14 10 30 20

I've adjusted this part logic, please refer to the lastest commit: https://github.com/xorbitsai/inference/pull/2039/commits/bb4aca12dfd6904419e5c0207ad39ca1e0408d31

**Review by yiboyasss — APPROVED** [review]

**Comment by qinxuye** [comment]
Thanks for your contribution!

**Pull request merged**
