### PR TITLE
BUG: fix subprocess log on linux

### PR DESCRIPTION
**Pull request by UranusSeven**

### CODE REVIEW

**Comment by aresnow1** [comment]
Does it work?

**Comment by UranusSeven** [comment]
The subprocess logging still doesn't work.

**Comment by aresnow1** [comment]
It works on my machine for python 3.11, you can see different pid in logs:
```
2023-08-25 22:20:27,033 xinference.core.worker 1142182 DEBUG    Subpool selected: 127.0.0.1:41309, running model count: 0
launch done
2023-08-25 22:20:28,741 xinference.core.model 1142271 DEBUG    launch done===========================
```

**Review by aresnow1 — APPROVED** [review]
LGTM

**Pull request merged**
